#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

# FIXME: on ubuntu I get an error that I can't link the static (or shared!) library
# without this, even though it should be fine with -fPIC, so use this hack
env["STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME"] = '1'

alternis_dep = "../../lib/zig-out/lib/libalternis.a"

env.Append(CPPPATH=["src/", "../../lib/headers-gen"])
sources = Glob("src/*.cpp") + [alternis_dep]

env.Append(LIBS=['c'])

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "lib/libalternis-godot.{}.{}.framework/libalternis-godot.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "lib/libalternis-godot{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
